export enum Status {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ORDERED = 'ORDERED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  DELIVERED = 'DELIVERED',
  DELETED = 'DELETED',
}
